### ISSUE TITLE
如何实现动态数据源的配置

### ISSUE THREAD

**Issue by lecion** [tencent-cdc/formast#10]
例如：
- 有一个选项列表，选项数据源来自于 ajax 请求
- 有一个搜索控件，搜索结果来自于 ajax 请求

**Comment by tangshuang** [comment]
你说的其实是两种情况，这里先简单说下区别。
选项列表无论是给定的，还是ajax请求回来的，都是有限的列表数据。而搜索结果是无限的。

搜索控件的搜索过程和UI处理应该由组件完成，对于表单而言，该组件和input没有本质区别。
选项列表中的选项则和搜索不同，往往是由业务决定的，所以，我会把选项信息放在模型中进行管理。由于考虑到数据量大，一般会考虑将数据暂存在后端，异步请求，请求的的参数，由当前整个表单临时的状态来决定。
因此，对于我而言，只会考虑你讲的第一种，搜索会用一个高阶的搜索输入框组件实现。

联动下拉用schema表达如下：

```
{
  model: {
    dodoit: {
       default: 0,
       options: [
         { label: 'can', value: 1 },
         { label: 'can not', value: 0 }
        ],
        component: 'Select'
    },
    check_canbi: {
       default: '',
       options: "{ []:fetch('https://xxx/api/canbi?s=' + dodoit) }",
       component: 'Select'
    },
  },

  layout: [
    { bind: 'dodoit' },
    { bind: 'check_canbi' }
  ]
}
```

解释一下，check_canbi这个字段的options使用了AsyncGetter语法，也就是动态取值的语法，默认值是[]，然后会根据dodoit的值去请求接口得到结果后，把结果作为新值给options，更新界面。当dodoit切换时，因为语法里面分析出依赖了dodoit，所以请求会被再次发出，options的值会发生变化，界面上列表也会更新。这样就做到了字段A的下拉选项列表与字段B的值联动了。

需要明确一点，下拉列表信息实际上可以直接写在模型里面，只是鉴于前后端交互的特质，可以通过这种数据分离的方式用接口切割。如果直接放在模型里，可以这么写：

```
{
    "options": "{ dodoit === 0 ? [ ....列表A ] : [ ...列表B ] }"
}
```

也是动态语法，它会根据dodoit的值而发生变化（原理不同，上面一种是通过分析发现依赖dodoit字段，于是做了一个监听，而此处是因为options是一个计算属性，每次读取的时候，都会执行dodoit === 0的逻辑判断）。

指出这一点的原因是，options 会被放在模型中，作为该字段的一项元数据，而非交互上的一个临时状态。

**Comment by strayerM** [comment]
有2个疑问：这个 fetch 是自定义的 ajax 请求函数吗？

**Comment by strayerM** [comment]
有2个疑问：1. 这个 fetch 是自定义的 ajax 请求函数吗？2. 能实现 fetch
 后对返回的数据处理后再返回给 options 吗？

**Comment by strayerM** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API

那这个能使用自己项目里封装的 axios 请求吗

**Comment by tangshuang** [comment]
> 

文档里面有专门介绍过 fetch 配置项 https://formast.js.org/#/parser?id=options
