### ISSUE TITLE
如何实现表单的数据回显

### ISSUE THREAD

**Issue by strayerM** [tencent-cdc/formast#16]
场景：用于功能配置的表单在填写并提交给后台后，再次打开这个表单需要回显之前填写的内容

**Comment by tangshuang** [comment]
感谢反馈，已经更新版本。

数据回显需要和你定义的Model对应，表单基于Model进行渲染。在使用组件或创建实例的时候，要传入对应的模型初始数据，例如：

```js
<Formast schema={getSchema} data={getData} options={OPTIONS}></Formast>
```

已经在文档中增加了对应的说明。https://formast.js.org/#/react

**Comment by strayerM** [comment]
感谢更新
