### ISSUE TITLE
可视化编辑的问题

### ISSUE THREAD

**Issue by strayerM** [tencent-cdc/formast#17]
文档对于 [Schema](https://formast.js.org/#/schema?id=schema) 数据结构说明中提到了编辑器解析Schema JSON生成编辑器界面，请问有编辑器相关的示例吗

**Comment by tangshuang** [comment]
可视化编辑器方案还不够完善，如果表单需求不复杂，可通过其他可视化编辑器生成 schema 即可，从可视化编辑器生成 schema 这个过程与 formast 没有强制关联性，你可以用任意的可视化编辑器生成，只要最终生成的 schema 为 formast 定义的 schema 即可
