### ISSUE TITLE
运行时动态注册 single json scheme

### ISSUE THREAD

**Issue by StringKe** [tencent-cdc/formast#24]
在运行时候往 context 动态增改组件比如

```tsx
<FormProvider from={from}>
    <SchemaFiled name=xxx/>
    {props.xx && (<SchemaFiled name=xxx/>)}
</Form>
```

将渲染的逻辑开放出来

**Comment by StringKe** [comment]
@tangshuang 大佬麻烦看一下，实现麻烦么。

**Comment by tangshuang** [comment]
使用visible https://formast.js.org/#/schema?id=%e7%bb%84%e4%bb%b6

**Comment by StringKe** [comment]
默认传给 Formast 的 schema 可以传递一个 visible 为 false 的组件么，然后应该怎么动态的添加一个呢？

**Comment by tangshuang** [comment]
"visible": "{ x > 1 }"

认真阅读一下文档，你这种需求属于基本操作

**Comment by StringKe** [comment]
没有理解，我看完文档，整个表单内容都是由 JSON 控制，我默认不存在这个 JSON ，如何去设置 visible 呢？

我控制的是 children 中的组件，而不是 JSON 。

```
<Formast>
      <Filed name="aa"/> // Filed 是由后续操作新增进来的，而不是 JSON 传递渲染。
</Format>
```

**Comment by tangshuang** [comment]
你这个操作很奇怪，我没有提供field这样的组件，也不应该这样去操作。你应该用json去驱动你的表单。
